// let imgHttp = "http://localhost:3000/images/fight_the_landlords"
// const imgHttp = "/fight_the_landlords";

const PokerResource = {
    images: [
        { name: "大王", point: 15, url: "/fight_the_landlords/1.jpg" },
        { name: "小王", point: 14, url: "/fight_the_landlords/2.jpg" },
        { name: "黑桃3", point: 1, url: "/fight_the_landlords/3.jpg" },
        { name: "黑桃4", point: 2, url: "/fight_the_landlords/4.jpg" },
        { name: "黑桃5", point: 3, url: "/fight_the_landlords/5.jpg" },
        { name: "黑桃6", point: 4, url: "/fight_the_landlords/6.jpg" },
        { name: "黑桃7", point: 5, url: "/fight_the_landlords/7.jpg" },
        { name: "黑桃8", point: 6, url: "/fight_the_landlords/8.jpg" },
        { name: "黑桃9", point: 7, url: "/fight_the_landlords/9.jpg" },
        { name: "黑桃10", point: 8, url: "/fight_the_landlords/10.jpg" },
        { name: "黑桃J", point: 9, url: "/fight_the_landlords/11.jpg" },
        { name: "黑桃Q", point: 10, url: "/fight_the_landlords/12.jpg" },
        { name: "黑桃K", point: 11, url: "/fight_the_landlords/13.jpg" },
        { name: "黑桃A", point: 12, url: "/fight_the_landlords/14.jpg" },
        { name: "黑桃2", point: 13, url: "/fight_the_landlords/15.jpg" },
        { name: "红桃3", point: 1, url: "/fight_the_landlords/16.jpg" },
        { name: "红桃4", point: 2, url: "/fight_the_landlords/17.jpg" },
        { name: "红桃5", point: 3, url: "/fight_the_landlords/18.jpg" },
        { name: "红桃6", point: 4, url: "/fight_the_landlords/19.jpg" },
        { name: "红桃7", point: 5, url: "/fight_the_landlords/20.jpg" },
        { name: "红桃8", point: 6, url: "/fight_the_landlords/21.jpg" },
        { name: "红桃9", point: 7, url: "/fight_the_landlords/22.jpg" },
        { name: "红桃10", point: 8, url: "/fight_the_landlords/23.jpg" },
        { name: "红桃J", point: 9, url: "/fight_the_landlords/24.jpg" },
        { name: "红桃Q", point: 10, url: "/fight_the_landlords/25.jpg" },
        { name: "红桃K", point: 11, url: "/fight_the_landlords/26.jpg" },
        { name: "红桃A", point: 12, url: "/fight_the_landlords/27.jpg" },
        { name: "红桃2", point: 13, url: "/fight_the_landlords/28.jpg" },
        { name: "梅花3", point: 1, url: "/fight_the_landlords/29.jpg" },
        { name: "梅花4", point: 2, url: "/fight_the_landlords/30.jpg" },
        { name: "梅花5", point: 3, url: "/fight_the_landlords/31.jpg" },
        { name: "梅花6", point: 4, url: "/fight_the_landlords/32.jpg" },
        { name: "梅花7", point: 5, url: "/fight_the_landlords/33.jpg" },
        { name: "梅花8", point: 6, url: "/fight_the_landlords/34.jpg" },
        { name: "梅花9", point: 7, url: "/fight_the_landlords/35.jpg" },
        { name: "梅花10", point: 8, url: "/fight_the_landlords/36.jpg" },
        { name: "梅花J", point: 9, url: "/fight_the_landlords/37.jpg" },
        { name: "梅花Q", point: 10, url: "/fight_the_landlords/38.jpg" },
        { name: "梅花K", point: 11, url: "/fight_the_landlords/39.jpg" },
        { name: "梅花A", point: 12, url: "/fight_the_landlords/40.jpg" },
        { name: "梅花2", point: 13, url: "/fight_the_landlords/41.jpg" },
        { name: "方块3", point: 1, url: "/fight_the_landlords/42.jpg" },
        { name: "方块4", point: 2, url: "/fight_the_landlords/43.jpg" },
        { name: "方块5", point: 3, url: "/fight_the_landlords/44.jpg" },
        { name: "方块6", point: 4, url: "/fight_the_landlords/45.jpg" },
        { name: "方块7", point: 5, url: "/fight_the_landlords/46.jpg" },
        { name: "方块8", point: 6, url: "/fight_the_landlords/47.jpg" },
        { name: "方块9", point: 7, url: "/fight_the_landlords/48.jpg" },
        { name: "方块10", point: 8, url: "/fight_the_landlords/49.jpg" },
        { name: "方块J", point: 9, url: "/fight_the_landlords/50.jpg" },
        { name: "方块Q", point: 10, url: "/fight_the_landlords/51.jpg" },
        { name: "方块K", point: 11, url: "/fight_the_landlords/52.jpg" },
        { name: "方块A", point: 12, url: "/fight_the_landlords/53.jpg" },
        { name: "方块2", point: 13, url: "/fight_the_landlords/54.jpg" },
        { name: "bgImage", url: "/fight_the_landlords/bg1.png" },
        { name: "startBtn", url: "/fight_the_landlords/kaishi.png" },
        { name: "不抢", data: 0, url: "/fight_the_landlords/buqiang.png" },
        { name: "抢地主",data:1, url:"/fight_the_landlords/qiangdizhu.png"},
        // { name: "one", socre: 1, url: "/fight_the_landlords/yf.png" },
        // { name: "two", socre: 2, url: "/fight_the_landlords/ef.png" },
        // { name: "three", socre: 3, url: "/fight_the_landlords/sf.png" },
        { name: "pokerBack", url: "/fight_the_landlords/pokerback.png" },
        { name: "不出", url: "/fight_the_landlords/buchu.png" },
        { name: "提示", url: "/fight_the_landlords/tishi.png" },
        { name: "出牌", url: "/fight_the_landlords/chupai.png" }
    ]
}

export default PokerResource;